# railway.toml

[envs]
  PYTHON = "python"
  
[build]
  commands = [
    "npm install",
    "pip install -r requirements.txt"
  ]

[start]
  command = "python app-11.py"  # Reemplaza "app-11.py" con el nombre del archivo principal de tu proyecto
